<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Home' => '首页',
	'Article' => '文章',
	
	'Message' => '信息',
	'Comment' => '评论',
	'Login' => '登录',
	'Logout' => '注销',
    'Signup' => '注册',
	'Name' => '名称',
	'User Name' => '用户名',
	'Password' => '密码',
	'Avatar' => '头像',
	'Profile' => '个人中心',
	'Incorrect username or password.' => '用户名或密码错误',
	
	'Add' => '新增',
	'Create' => '新增',
	'Update' => '更新',
	'Delete' => '删除',
    'Error' => '错误',
    'View' => '查看',
	'Close' => '关闭',
	
	'Title' => '标题',
	'Thumb' => '缩略图',
	'Detail' => '内容',
	'Summary' => '摘要',
	'Category Top' => '顶级分类',
	
    'Yes' => '是',
	'No' => '否',	
	
	'Submit' => '提交',
	'Reset' => '重置',
	'Search' => '搜索',
	'Upload' => '上传',
	'Sorting' => '排序',
	'Status' => '状态',
	'Url' => '链接',
	
	'Updated At' => '更新时间',
	'Created At' => '创建时间',
	
	'Can not be empty' => '不能为空',
	'Please select' => '请选择',
	'Verify code' => '验证码',
	
];
